# 
# File: front-end/docker-compose.yml
# 
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5000
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    env_file:
      - ./.env
    networks:
      - app-network

networks:
  app-network: