# 
# File: back-end/docker-compose.yml
# 
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    networks:
      - app-network

networks:
  app-network: